model = "gpt-5.5"
model_reasoning_effort = "xhigh"
sandbox_mode = "workspace-write"
approval_policy = "on-request"

notify = ["/Users/thomashexton/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/thomashexton"]
trust_level = "trusted"

[projects."/Users/thomashexton/nixfiles"]
trust_level = "trusted"

[projects."/home/thomashexton"]
trust_level = "trusted"

[projects."/home/thomashexton/nixfiles"]
trust_level = "trusted"

[projects."/Users/thomashexton/qmk"]
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true

[features]
multi_agent = true
js_repl = false

[plugins."github@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[mcp_servers.nixos]
command = "mcp-nixos"

[mcp_servers.nixos.tools.darwin_search]
approval_mode = "approve"

[mcp_servers.nixos.tools.home_manager_options_by_prefix]
approval_mode = "approve"

[mcp_servers.nixos.tools.darwin_options_by_prefix]
approval_mode = "approve"

[mcp_servers.nixos.tools.home_manager_info]
approval_mode = "approve"

[mcp_servers.nixos.tools.darwin_info]
approval_mode = "approve"

[mcp_servers.nixos.tools.nixos_search]
approval_mode = "approve"

[mcp_servers.nixos.tools.nixos_info]
approval_mode = "approve"

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/thomashexton/.codex"
CODEX_HOME = "/Users/thomashexton/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "5b74180ac40ca4cf726cad15c5ff886f159224f1c0306ea364ad9eea6a7e7ac2,6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.715.21425"
SKY_CUA_SERVICE_PATH = "/Users/thomashexton/.codex/plugins/cache/openai-bundled/computer-use/1.0.1000451/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[tui]
session_picker_view = "dense"

[tui.model_availability_nux]
"gpt-5.5" = 4

[notice.model_migrations]
"gpt-5.4" = "gpt-5.5"

[marketplaces.openai-bundled]
last_updated = "2026-07-18T00:15:23Z"
source_type = "local"
source = "/Users/thomashexton/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-04-25T10:35:24Z"
source_type = "local"
source = "/Users/thomashexton/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[desktop]
default-service-tier = "fast"
followUpQueueMode = "queue"
dock-icon-preference = "app-default"
conversationDetailMode = "STEPS_COMMANDS"
selected-avatar-id = "rocky"
git-branch-prefix = "codex-"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/thomashexton/qmk" = "zed"

[shell_environment_policy.set]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "5b74180ac40ca4cf726cad15c5ff886f159224f1c0306ea364ad9eea6a7e7ac2,6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/thomashexton/.codex"
